version: '1.1'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./TiendaWeb-1/TiendaWeb-1/:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: store
            MYSQL_USER: isaac
            MYSQL_PASSWORD: admin1234
        volumes:
            - ./TiendaWeb-1/store:/var/lib/mysql
            - ./TiendaWeb-1/store.sql:/docker-entrypoint-initdb.d/dump.sql
        ports:
            - "9906:3306"
